### ISSUE TITLE
Cant Create Run

### ISSUE THREAD

**Issue by extr3mal** [gennadii-borodin/robotframework-traillibrary#2]
`python createtestrun.py -user ****** -url https://******* -key ******* -project "Test Integration" -run "Automation Run" -d "Set
of automated tests" -plan "Desktop Tests"
''
''
'Arguments:'
'=========='
[('case_ids', '[]'),
 ('configset', '[]'),
 ('project', 'Test Integration'),
 ('run_description', 'Set of automated tests'),
 ('test_plan', 'Desktop Tests'),
 ('test_run', 'Automation Run'),
 ('test_suite', 'Master'),
 ('tr_key', '********'),
 ('tr_url', '******'),
 ('tr_user', '******')]
Traceback (most recent call last):
  File "C:\Python37\Lib\site-packages\TRailLibrary\createtestrun.py", line 78, in <module>
    main()
  File "C:\Python37\Lib\site-packages\TRailLibrary\createtestrun.py", line 63, in main
    test_rail.select_plan(args.test_plan)
  File "C:\Python37\lib\site-packages\TRailLibrary\test_rail_adaptor.py", line 64, in select_plan
    self.plan = self._get_plan(self.project.id, new_plan_name)
  File "C:\Python37\lib\site-packages\TRailLibrary\test_rail_adaptor.py", line 25, in _wrapper
    return func_to_connect(self, *args, **kwargs)
  File "C:\Python37\lib\site-packages\TRailLibrary\test_rail_adaptor.py", line 173, in _get_plan
    raise ValueError("Can't find plan '{name}'".format(name=plan_name))
ValueError: Can't find plan 'Desktop Tests'`

Also is it possible to create test run without plan ?

**Comment by gennadii-borodin** [comment]
The error means that you do not have the plan in TR.

At the moment the implementation does not support runs which are not organized with plans
